var SLConfig = {
	deck: {
		id: 1953231,
		slug: "etjseventloop",
		title: "JavaScript Event Loop Explained",
		description: "",
		width: 1280,
		height: 720,
		margin: 0.05,
		visibility: "all",
		published_at: "2020-10-21T18:14:18.076Z",
		sanitize_messages: null,
		thumbnail_url: "https://s3.amazonaws.com/media-p.slid.es/thumbnails/7f78951ff953de97f335d38ab31efef7/thumb.jpg?1603388126",
		view_count: 1,
		user: {
			id: 1464811,
			username: "andresperez-10",
			name: "Andres Perez",
			description: null,
			thumbnail_url: "https://lh3.googleusercontent.com/a-/AOh14GgMlOHae-wiEgAAdBH1PVscPdTdYZbvzbFjdyG8yQ=s96-c",
			account_type: "lite",
			team_id: null,
			settings: {
				id: 6621851,
				present_controls: true,
				present_upsizing: true,
				present_pointer: true,
				present_notes: true,
				default_deck_tag_id: null,
			},
		},
		background_transition: "slide",
		transition: "slide",
		theme_id: null,
		theme_font: "montserrat",
		theme_color: "white-blue",
		auto_slide_interval: 0,
		comments_enabled: true,
		forking_enabled: true,
		rolling_links: false,
		center: false,
		shuffle: false,
		should_loop: false,
		share_notes: false,
		slide_number: false,
		slide_count: 2,
		rtl: false,
		version: 2,
		collaborative: null,
		deck_user_editor_limit: 1,
		data_updated_at: 1603562402601,
		font_typekit: null,
		font_google: null,
		time_limit: null,
		navigation_mode: "default",
		upsizing_enabled: true,
		notes: {},
	},
};

// Use local fonts
SLConfig.fonts_url = "lib/fonts/";
